message("\tCMAKE_CURRENT_SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR}, CMAKE_SOURCE_DIR=${CMAKE_SOURCE_DIR}")
message("\tCMAKE_CURRENT_BINARY_DIR=${CMAKE_CURRENT_BINARY_DIR}, CMAKE_BINARY_DIR=${CMAKE_BINARY_DIR}")
